name: Java CI Pipeline
on: workflow_dispatch

jobs:
  first-flow:
    runs-on: ubuntu-latest
    steps:
      - name: prnit greeting
        run: echo"Greetings"
      - name: Set up JDK 17
        run: echo"Greetings java 17"        
      - name: Build with Maven
        run: echo "Done"
